# 1 R语言数据可视化简介

## 1.1 R语言介绍
R是一种编程语言和自由软件，常用于统计计算和图形绘制。

详细内容参考链接：

https://baike.baidu.com/item/R%E8%AF%AD%E8%A8%80/4090790?fr=aladdin

### 1.1.1 向量
向量即一组数据。

In [2]:
#创建一个向量
letter <- c("a","b","c")
letter

[1] "a" "b" "c"

上面代码用c()创建了一个向量，包含三个元素。

In [3]:
# 查看数据类型
class(letter)

[1] "character"

In [6]:
letter[1]# 提取向量中的第一个元素

[1] "a"

### 1.1.2 列表
* 列表（lsit）通常用于存储不同数据类型的数据。
* 列表中包含了：向量、列表、数组、矩阵、数据框这几种数据结构。
* 列表可以进行嵌套多层。

In [14]:
l <- list(c(1,2,3),
          list(1),
          array(c(1,2,3,3,1,2)),
          dim = c(1,2,3),
          matrix(c(1,2,3,4),nrow = 2),
          factor(c(1,2,3)),
          data.frame(nu = c(1:3)),
          id = c("a","b","c")
         )
l

[[1]]
[1] 1 2 3

[[2]]
[[2]][[1]]
[1] 1


[[3]]
[1] 1 2 3 3 1 2

$dim
[1] 1 2 3

[[5]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[[6]]
[1] 1 2 3
Levels: 1 2 3

[[7]]
  nu
1  1
2  2
3  3

$id
[1] "a" "b" "c"

* 上面代码创建了6种类型的数据。
* 提取列表中的元素，使用[[]]。l[[1]]表示提取列表里面的第一个元素.
* 希望进一步提取向量中的元素，使用[[]][],例如 l[[1]][1],表示提取第一个元素的第一个元素。

In [15]:
l[[1]]

[1] 1 2 3

In [24]:
l[[1]][1]

[1] 1

### 1.1.3 矩阵
矩阵可以理解为二维数组，可以使用矩阵函数(matrix)来创建。

In [25]:
M = matrix(c('c','a','b','c','b','a'),nrow = 2,ncol = 3,byrow = TRUE)
# ncol 矩阵列数
# nrow 矩阵行数
# byrow = TRUE  简单写为 byrow = T通过行排列
print(M)

     [,1] [,2] [,3]
[1,] "c"  "a"  "b" 
[2,] "c"  "b"  "a" 


In [28]:
M[1,3] #选取 第1行 第三列，提取某一个矩阵的元素用[,]前行后列

[1] "b"

### 1.1.4 数组

In [1]:
#创建一个数组
a <- array(c("green","yellow"),dim = c(3,3,2))# 创建了一个3*3*2的数组，dim参数表示有两个3*3的矩阵
print(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 

, , 2

     [,1]     [,2]     [,3]    
[1,] "yellow" "green"  "yellow"
[2,] "green"  "yellow" "green" 
[3,] "yellow" "green"  "yellow"



In [3]:
a <- array(c("green","yellow"),dim = c(3,3,3))
print(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 

, , 2

     [,1]     [,2]     [,3]    
[1,] "yellow" "green"  "yellow"
[2,] "green"  "yellow" "green" 
[3,] "yellow" "green"  "yellow"

, , 3

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 



### 1.1.5 因子
 * 因子类型的数据有顺序的。
 * R中使用factor函数创建因子，函数中的levels参数用于指定因子中分类变量的顺序。

In [4]:
#创建一个颜色向量
apple_colors <- c("green","green","yellow","red","red","green")

In [5]:
#创建一个因子向量
factor_apple <- factor(apple_colors)

In [6]:
#输出结果
print(factor_apple)

[1] green  green  yellow red    red    green 
Levels: green red yellow


In [7]:
print(nlevels(factor_apple))

[1] 3
