# 1 R语言数据可视化简介

## 1.1 R语言介绍
R是一种编程语言和自由软件，常用于统计计算和图形绘制。

详细内容参考链接：

https://baike.baidu.com/item/R%E8%AF%AD%E8%A8%80/4090790?fr=aladdin

### 1.1.1 向量
向量即一组数据。

In [2]:
#创建一个向量
letter <- c("a","b","c")
letter

[1] "a" "b" "c"

上面代码用c()创建了一个向量，包含三个元素。

In [3]:
# 查看数据类型
class(letter)

[1] "character"

In [6]:
letter[1]# 提取向量中的第一个元素

[1] "a"

### 1.1.2 列表
* 列表（lsit）通常用于存储不同数据类型的数据。
* 列表中包含了：向量、列表、数组、矩阵、数据框这几种数据结构。
* 列表可以进行嵌套多层。

In [14]:
l <- list(c(1,2,3),
          list(1),
          array(c(1,2,3,3,1,2)),
          dim = c(1,2,3),
          matrix(c(1,2,3,4),nrow = 2),
          factor(c(1,2,3)),
          data.frame(nu = c(1:3)),
          id = c("a","b","c")
         )
l

[[1]]
[1] 1 2 3

[[2]]
[[2]][[1]]
[1] 1


[[3]]
[1] 1 2 3 3 1 2

$dim
[1] 1 2 3

[[5]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[[6]]
[1] 1 2 3
Levels: 1 2 3

[[7]]
  nu
1  1
2  2
3  3

$id
[1] "a" "b" "c"

* 上面代码创建了6种类型的数据。
* 提取列表中的元素，使用[[]]。l[[1]]表示提取列表里面的第一个元素.
* 希望进一步提取向量中的元素，使用[[]][],例如 l[[1]][1],表示提取第一个元素的第一个元素。

In [15]:
l[[1]]

[1] 1 2 3

In [24]:
l[[1]][1]

[1] 1

### 1.1.3 矩阵
矩阵可以理解为二维数组，可以使用矩阵函数(matrix)来创建。

In [25]:
M = matrix(c('c','a','b','c','b','a'),nrow = 2,ncol = 3,byrow = TRUE)
# ncol 矩阵列数
# nrow 矩阵行数
# byrow = TRUE  简单写为 byrow = T通过行排列
print(M)

     [,1] [,2] [,3]
[1,] "c"  "a"  "b" 
[2,] "c"  "b"  "a" 


In [28]:
M[1,3] #选取 第1行 第三列，提取某一个矩阵的元素用[,]前行后列

[1] "b"

### 1.1.4 数组

In [1]:
#创建一个数组
a <- array(c("green","yellow"),dim = c(3,3,2))# 创建了一个3*3*2的数组，dim参数表示有两个3*3的矩阵
print(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 

, , 2

     [,1]     [,2]     [,3]    
[1,] "yellow" "green"  "yellow"
[2,] "green"  "yellow" "green" 
[3,] "yellow" "green"  "yellow"



In [3]:
a <- array(c("green","yellow"),dim = c(3,3,3))
print(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 

, , 2

     [,1]     [,2]     [,3]    
[1,] "yellow" "green"  "yellow"
[2,] "green"  "yellow" "green" 
[3,] "yellow" "green"  "yellow"

, , 3

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 



### 1.1.5 因子
 * 因子类型的数据有顺序的。
 * R中使用factor函数创建因子，函数中的levels参数用于指定因子中分类变量的顺序。

In [4]:
#创建一个颜色向量
apple_colors <- c("green","green","yellow","red","red","green")

In [5]:
#创建一个因子向量
factor_apple <- factor(apple_colors)

In [6]:
#输出结果
print(factor_apple)

[1] green  green  yellow red    red    green 
Levels: green red yellow


In [7]:
print(nlevels(factor_apple))

[1] 3


一般而言，字符数据不能进行比较，但是如果设成因子，则表示字符是有顺序的。

### 1.1.6 数据框 
* 据框 表格数据对象。
* 数据框 每列可以包含不同类型的数据。
* 数据框 等长度向量的组合。

In [2]:
# 创建一个数据框
BMI <- data.frame(
gender = c("Male","Male","Female"),
height = c(152,171.5,165),
Age = c(42,38,26))
print(BMI)# 创建了一个数据

  gender height Age
1   Male  152.0  42
2   Male  171.5  38
3 Female  165.0  26


整洁数据：
* 每一个变量都是一列
* 每一个观测都是一行
* 每一种类型的观察值一起构成一个表格

### 1.1.7 for 循环
for 循环是一种程序控制结构，用于实现特定次数的循环。

In [4]:
# 在R中创建一个for循环语句的基本格式如下:
for (test_expression){
    statement
}

R 的for循环特别灵活，它的循环变量，不限于整数，任何向量都可以通过for循环进行变量
我们可以传递字符向量、逻辑向量、列表或表达式。

In [5]:
# for 循环
v <- LETTERS[1:4]
for (i in v){ # i遍历v里面的变量
    print(i)
}

[1] "A"
[1] "B"
[1] "C"
[1] "D"


In [6]:
# apply 函数
a  <- data.frame(v)
apply(a,1,print)

  v 
"A" 
  v 
"B" 
  v 
"C" 
  v 
"D" 


[1] "A" "B" "C" "D"

### 1.1.8 条件判断
* 条件判断是代码中非常重要的程序控制方法。
* 在R中创建if… else 语句

In [ ]:
#if… else  基本语法
if (boolean_expression){
    ## 为真时的执行
} else { 
    ## 为假时的执行
}